#!/bin/bash

echo \
"CREATE DATABASE IF NOT EXISTS $CLIENT_DB_NAME;
USE $CLIENT_DB_NAME;
CREATE TABLE IF NOT EXISTS $CLIENT_DB_TABLE_NAME (
    id varchar(50) NOT NULL,
    name varchar(50),
    plan varchar(20),
    token varchar(100),
    PRIMARY KEY (ID)
);
CREATE USER '$CLIENT_DB_USERNAME'@'%' IDENTIFIED BY '$CLIENT_DB_PASSWORD';
GRANT ALL ON $CLIENT_DB_NAME.* TO '$CLIENT_DB_USERNAME'@'%';"
